-- NovaRAG Database Schema Setup for RDS PostgreSQL
-- Run this after the RDS instance is created

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Create site_pages table
CREATE TABLE IF NOT EXISTS site_pages (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  url TEXT NOT NULL,
  chunk_number INT DEFAULT 0,
  title TEXT,
  summary TEXT,
  content TEXT,
  metadata JSONB DEFAULT '{}',
  embedding vector(1024),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS site_pages_embedding_idx ON site_pages
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

CREATE INDEX IF NOT EXISTS site_pages_url_chunk_idx ON site_pages(url, chunk_number);
CREATE INDEX IF NOT EXISTS site_pages_metadata_idx ON site_pages USING gin(metadata);

-- Create match_site_pages function for vector search
CREATE OR REPLACE FUNCTION match_site_pages (
  query_embedding vector(1024),
  match_count int DEFAULT 5,
  filter_config jsonb DEFAULT '{}'
) RETURNS TABLE (
  id bigint,
  url text,
  chunk_number int,
  title text,
  summary text,
  content text,
  metadata jsonb,
  embedding vector(1024),
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN query
  SELECT
    sp.id,
    sp.url,
    sp.chunk_number,
    sp.title,
    sp.summary,
    sp.content,
    sp.metadata,
    sp.embedding,
    1 - (sp.embedding <=> query_embedding) AS similarity
  FROM site_pages sp
  WHERE sp.metadata @> filter_config
  ORDER BY sp.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Create query_history table for tracking queries
CREATE TABLE IF NOT EXISTS query_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_query TEXT NOT NULL,
  final_answer TEXT,
  validation_passed BOOLEAN,
  tools_used JSONB DEFAULT '{}',
  attempts INT DEFAULT 1,
  latency_ms INT,
  input_tokens INT,
  output_tokens INT,
  estimated_cost_usd DECIMAL(10, 6),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS query_history_created_idx ON query_history(created_at DESC);
CREATE INDEX IF NOT EXISTS query_history_validation_idx ON query_history(validation_passed);

-- Create update_updated_at_column function and trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_site_pages_updated_at ON site_pages;

CREATE TRIGGER update_site_pages_updated_at
    BEFORE UPDATE ON site_pages
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
