#!/usr/bin/env python3
"""Setup database schema for NovaRAG."""

import boto3
import psycopg2
from dotenv import load_dotenv
import os

# Get RDS credentials from CloudFormation
session = boto3.session.Session(region_name='ap-southeast-2')
cf = session.client('cloudformation')

stack = cf.describe_stacks(StackName='nova-rag-db-v2')['Stacks'][0]
outputs = {out['OutputKey']: out['OutputValue'] for out in stack['Outputs']}

DB_ENDPOINT = outputs['DBEndpoint']
DB_PORT = outputs['DBPort']
DB_NAME = outputs['DBName']
DB_USER = outputs['MasterUsername']
DB_SECRET_ARN = outputs['DBSecretArn']

# Get password from Secrets Manager
import json
sm = session.client('secretsmanager')
secret = sm.get_secret_value(SecretId=DB_SECRET_ARN)
DB_PASSWORD = json.loads(secret['SecretString'])['password']

print(f"Connecting to {DB_ENDPOINT}:{DB_PORT}/{DB_NAME}...")

# Connect and setup schema
conn = psycopg2.connect(
    host=DB_ENDPOINT,
    port=int(DB_PORT),
    database=DB_NAME,
    user=DB_USER,
    password=DB_PASSWORD,
    connect_timeout=10
)
conn.autocommit = True
cursor = conn.cursor()

print("Enabling pgvector extension...")
cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")

print("Creating site_pages table...")
cursor.execute("""
    CREATE TABLE IF NOT EXISTS site_pages (
      id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
      url TEXT NOT NULL,
      chunk_number INT DEFAULT 0,
      title TEXT,
      summary TEXT,
      content TEXT,
      metadata JSONB DEFAULT '{}',
      embedding vector(1024),
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    );
""")

print("Creating indexes...")
cursor.execute("""
    CREATE INDEX IF NOT EXISTS site_pages_embedding_idx
    ON site_pages USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);
""")
cursor.execute("""
    CREATE INDEX IF NOT EXISTS site_pages_url_chunk_idx
    ON site_pages(url, chunk_number);
""")
cursor.execute("""
    CREATE INDEX IF NOT EXISTS site_pages_metadata_idx
    ON site_pages USING gin(metadata);
""")

print("Creating match_site_pages function...")
cursor.execute("""
    CREATE OR REPLACE FUNCTION match_site_pages (
      query_embedding vector(1024),
      match_count int DEFAULT 5,
      filter_config jsonb DEFAULT '{}'
    ) RETURNS TABLE (
      id bigint,
      url text,
      chunk_number int,
      title text,
      summary text,
      content text,
      metadata jsonb,
      embedding vector(1024),
      similarity float
    )
    AS $$
    BEGIN
      RETURN query
      SELECT
        sp.id,
        sp.url,
        sp.chunk_number,
        sp.title,
        sp.summary,
        sp.content,
        sp.metadata,
        sp.embedding,
        1 - (sp.embedding <=> query_embedding) AS similarity
      FROM site_pages sp
      WHERE sp.metadata @> filter_config
      ORDER BY sp.embedding <=> query_embedding
      LIMIT match_count;
    END;
    $$ LANGUAGE plpgsql;
""")

print("Creating query_history table...")
cursor.execute("""
    CREATE TABLE IF NOT EXISTS query_history (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_query TEXT NOT NULL,
      final_answer TEXT,
      validation_passed BOOLEAN,
      tools_used JSONB DEFAULT '{}',
      attempts INT DEFAULT 1,
      latency_ms INT,
      input_tokens INT,
      output_tokens INT,
      estimated_cost_usd DECIMAL(10, 6),
      created_at TIMESTAMPTZ DEFAULT NOW()
    );
""")

cursor.close()
conn.close()

print("Schema setup complete!")

# Update .env file
print("\nUpdating .env file...")
with open('.env', 'w') as f:
    f.write(f"AWS_REGION=ap-southeast-2\n")
    f.write(f"DB_HOST={DB_ENDPOINT}\n")
    f.write(f"DB_PORT={DB_PORT}\n")
    f.write(f"DB_NAME={DB_NAME}\n")
    f.write(f"DB_USER={DB_USER}\n")
    f.write(f"DB_PASSWORD={DB_PASSWORD}\n")

print("Deployment setup complete!")
